name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: start your project in the fastest way
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6 # for state management and context less stuff

  logger: ^2.6.0 # log events in clear way insted of (print)

  flutter_screenutil: ^5.9.3 # make app responsive

  dio: ^5.9.2 # for api requests
  http_mock_adapter: ^0.6.1 # mocking dio for testing
  pretty_dio_logger: ^1.4.0 # for dio api logging and debugging

  hive: ^2.2.3  # local database (SQFlite replacement)
  hive_flutter: ^1.1.0 # make it easy to use hive (no need for path provider)
  shared_preferences: ^2.5.4 # shared preferences persistence key value store

  firebase_core: ^4.5.0 # to initialize firebase services
  firebase_messaging: ^16.1.2 # fcm services
  awesome_notifications: ^0.11.0 # notifications services (will be used for fcm)

  rename_app: 1.4.0 # rename app

  flutter_svg: ^2.2.4  # display svg vectors

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: # for testing
  flutter_lints: # for linting and warningd
  build_runner:  # generate dart files
  hive_generator: # generate hive files
  pub_semver: ^2.1.4 # helper to generate hive models
  change_app_package_name: # change package name
  flutter_launcher_icons: ^0.14.4 # change app icon

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900

